name: shared_photo
description: Create memories that last with the people that matter.
publish_to: 'none'
version: 1.0.0+3-alpha

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auth0_flutter: ^1.5.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^5.1.0
  http: ^1.1.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  web_socket_channel: ^2.4.0
  carousel_slider: ^4.2.1
  camera: ^0.10.5+5
  buttons_tabbar: ^1.3.8
  dropdown_button2: ^2.3.9
  timeago: ^3.6.0
  gap: ^3.0.1
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - lib/assets/default.png
  - .env

