name: shared_photo
description: Create memories that last with the people that matter!
publish_to: 'none'
version: 1.0.9

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auth0_flutter: ^1.5.0
  bloc: ^8.1.2
  hydrated_bloc: ^9.1.5
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^6.2.1
  http: ^1.1.0
  image_picker: ^1.0.2
  intl: ^0.19.0
  web_socket_channel: ^3.0.1
  carousel_slider: ^5.0.0
  camera: ^0.11.0+2
  buttons_tabbar: ^1.3.8
  dropdown_button2: ^2.3.9
  timeago: ^3.6.0
  gap: ^3.0.1
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_udid: ^3.0.0
#  image_gallery_saver: ^2.0.3
  image_gallery_saver_plus: ^3.0.5
  image: ^4.2.0
  icon_decoration: ^2.0.2
  #path_provider: ^2.1.3
  animated_toggle_switch: ^0.8.2
  dio: ^5.5.0+1
  uuid: ^4.4.2
  dotted_border: ^2.1.0
  flutter_datetime_picker_plus: ^2.2.0
  omni_datetime_picker: ^2.0.5
  pinch_zoom_release_unzoom: ^1.0.3
  flutter_keychain: ^2.5.0
  pinch_to_zoom_scrollable: ^0.1.2


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - lib/assets/default.png
  - .env

