// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjxbI2qR9KZwL_eZAv_9G5UDhC4IDcxdo',
    appId: '1:833732196444:web:ee6ba39d263f4b7a5fce99',
    messagingSenderId: '833732196444',
    projectId: 'lastweekend',
    authDomain: 'lastweekend-a4864.firebaseapp.com',
    storageBucket: 'lastweekend.appspot.com',
    measurementId: 'G-0JCRXNXVCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHpiQbM0MzpDpnW9C3-JxTRjWNYSK4EZ4',
    appId: '1:833732196444:android:97b7921582015e435fce99',
    messagingSenderId: '833732196444',
    projectId: 'lastweekend',
    storageBucket: 'lastweekend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAHw3VZADarPLXdAE5ufa9kczG54R2IX8',
    appId: '1:833732196444:ios:640f2838d7dbca5d5fce99',
    messagingSenderId: '833732196444',
    projectId: 'lastweekend',
    storageBucket: 'lastweekend.appspot.com',
    iosBundleId: 'com.lastweekend.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAHw3VZADarPLXdAE5ufa9kczG54R2IX8',
    appId: '1:833732196444:ios:652aea3af18ddae45fce99',
    messagingSenderId: '833732196444',
    projectId: 'lastweekend',
    storageBucket: 'lastweekend.appspot.com',
    iosBundleId: 'com.example.sharedPhoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjxbI2qR9KZwL_eZAv_9G5UDhC4IDcxdo',
    appId: '1:833732196444:web:945f30a8237b1be15fce99',
    messagingSenderId: '833732196444',
    projectId: 'lastweekend',
    authDomain: 'lastweekend-a4864.firebaseapp.com',
    storageBucket: 'lastweekend.appspot.com',
    measurementId: 'G-32Q3B7E3X7',
  );
}
